### ISSUE TITLE
Bump version to get latest changes

### ISSUE THREAD

**Issue by joshje** [siddharthkp/bundlesize2#14]
Heya @siddharthkp, can you bump the package version so I can install the latest commit?

**Comment by siddharthkp** [comment]
My bad, I didn't redeploy the github reporter service. Done now 👍

**Comment by joshje** [comment]
Thanks @siddharthkp . Should it be available now? Still not seeing it here:
https://www.npmjs.com/package/bundlesize2

**Comment by siddharthkp** [comment]
The github reporter isn't part of the package. I'm guessing you're talking about this PR - https://github.com/siddharthkp/bundlesize2/pull/13

**Comment by joshje** [comment]
Yes, I'd like to get those images fixed in our CI pipeline, but there's no newer version of this package published yet.

The latest version on [npm](https://www.npmjs.com/package/bundlesize2) is 0.0.26 and doesn't include the fix to the SVG image location.

**Comment by siddharthkp** [comment]
Hi! the commit is in `github-reporter` which isn't published to npm, but instead deployed to vercel. I have deployed the latest version there.

**Comment by joshje** [comment]
No, I'm still seeing `https://raw.githubusercontent.com/siddharthkp/bundlesize2/master/github-reporter/public/check-pass.svg` as the URL in our GitHub checks, which is a broken image.

**Comment by siddharthkp** [comment]
Just checked, it's the right image now
